---
- hosts: localhost
  gather_facts: true  # Required to populate ansible_facts.services
  tasks:
    - name: Get list of running services
      ansible.builtin.debug:
        msg: "{{ ansible_facts.services | dict2items | selectattr('value.state', '==', 'running') | map(attribute='key') | list }}"